name: coverage-update

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  coverage-update:
    runs-on: ubuntu-latest
    steps:
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
        if: |
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'push'
        continue-on-error: true